#!/usr/bin/env python3
"""Rebuild the project index from the chapter files. Run after every change:

    python3 tools/build_index.py          # rewrite index/*.md and workbook/NAMES.md
    python3 tools/build_index.py --check  # exit 1 if anything is out of date or invalid

Chapter files live in novel/book-NN-slug/NN-slug.md and start with front
matter like:

    ---
    book: 1
    chapter: 4
    title: The Teacher's Pupils
    ce: [1.3.1-89]
    status: drafted          # planned | drafted | verified | revised
    summary: One line.
    ---

`ce` lists Critical Edition spans:  1.3 (whole adhyaya), 1.4-7 or 1.4-1.7
(whole adhyayas), 1.1.1-100 (verses of one adhyaya), 1.1.101-1.2.30 (across).

Outputs (all generated; do not edit by hand):
    index/CONTENTS.md         table of contents with status and word counts
    index/COVERAGE.md         which CE verses are covered, book by book
    index/CHARACTER_INDEX.md  where each named person appears
    workbook/NAMES.md         the names table, rendered from workbook/names.json
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOVEL = ROOT / "novel"
INDEX = ROOT / "index"
STRUCTURE = ROOT / "sources" / "ce_structure.json"
NAMES = ROOT / "workbook" / "names.json"

BOOKS = {
    1: ("Adi", "The Beginnings"), 2: ("Sabha", "The Assembly Hall"),
    3: ("Aranyaka", "The Forest"), 4: ("Virata", "The Year in Hiding"),
    5: ("Udyoga", "The Effort for Peace"), 6: ("Bhishma", "Bhishma's Battle"),
    7: ("Drona", "Drona's Battle"), 8: ("Karna", "Karna's Battle"),
    9: ("Shalya", "Shalya's Battle and the Mace Duel"), 10: ("Sauptika", "The Night Raid"),
    11: ("Stri", "The Women"), 12: ("Shanti", "Peace"), 13: ("Anushasana", "The Instructions"),
    14: ("Ashvamedhika", "The Horse Sacrifice"), 15: ("Ashramavasika", "The Hermitage"),
    16: ("Mausala", "The Iron Club"), 17: ("Mahaprasthanika", "The Great Journey"),
    18: ("Svargarohana", "The Ascent to Heaven"),
}
STATUSES = ["planned", "drafted", "verified", "revised"]
GENERATED = "<!-- Generated by tools/build_index.py. Do not edit by hand. -->\n"


# ---------------------------------------------------------------- parsing

def front_matter(text: str) -> dict:
    """Parse the small YAML subset used in chapter headers."""
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    meta = {}
    for line in text[3:end].splitlines():
        line = line.split(" #")[0].rstrip()
        if not line.strip() or ":" not in line:
            continue
        k, v = line.split(":", 1)
        v = v.strip()
        if v.startswith("[") and v.endswith("]"):
            meta[k.strip()] = [x.strip().strip("'\"") for x in v[1:-1].split(",") if x.strip()]
        else:
            v = v.strip("'\"")
            meta[k.strip()] = int(v) if re.fullmatch(r"\d+", v) else v
    return meta


def story_text(text: str) -> str:
    if text.startswith("---"):
        text = text[text.find("\n---", 3) + 4:]
    return text.split("<!-- notes -->")[0]


def word_count(text: str) -> int:
    return len(re.findall(r"[A-Za-z][A-Za-z'’-]*", story_text(text)))


def load_structure() -> dict[tuple[int, int], int]:
    data = json.loads(STRUCTURE.read_text(encoding="utf-8"))["books"]
    return {(int(b), int(a)): n for b, adh in data.items() for a, n in adh.items()}


def parse_span(span: str, struct) -> list[tuple[int, int, int, int]]:
    """Expand a CE span into (book, adhyaya, first_verse, last_verse) pieces."""
    s = span.replace("–", "-").strip()
    m = re.fullmatch(r"(\d+)\.(\d+)(?:\.(\d+))?(?:-(?:(\d+)\.)?(\d+)(?:\.(\d+))?)?", s)
    if not m:
        raise ValueError(f"cannot parse CE span {span!r}")
    b, a1, v1, b2, x, y = m.groups()
    b, a1 = int(b), int(a1)
    if x is None:                                    # 1.3 or 1.3.5
        a2, vend = a1, (int(v1) if v1 else None)
    elif v1 and b2 is None and y is None:             # 1.1.1-100
        a2, vend = a1, int(x)
    elif b2 is not None and y is not None:            # 1.1.101-1.2.30
        a2, vend = int(x), int(y)
    elif b2 is not None:                              # 1.4-1.7
        a2, vend = int(x), None
    else:                                             # 1.4-7
        a2, vend = int(x), None
    if b2 is not None and int(b2) != b:
        raise ValueError(f"span {span!r} crosses books")
    out = []
    for a in range(a1, a2 + 1):
        if (b, a) not in struct:
            raise ValueError(f"span {span!r}: CE {b}.{a} does not exist")
        n = struct[(b, a)]
        first = int(v1) if (a == a1 and v1) else 1
        last = vend if (a == a2 and vend) else n
        if a == a1 and v1 and a1 == a2 and x is None:
            last = first                              # single verse
        if not (1 <= first <= last <= n):
            raise ValueError(f"span {span!r}: verses {first}-{last} outside 1-{n} of CE {b}.{a}")
        out.append((b, a, first, last))
    return out


def load_chapters(struct):
    chapters, problems = [], []
    for f in sorted(NOVEL.glob("book-*/*.md")):
        if f.name.startswith(("00-", "README")):
            continue
        text = f.read_text(encoding="utf-8")
        meta = front_matter(text)
        rel = f.relative_to(ROOT)
        for key in ("book", "chapter", "title", "ce", "status"):
            if key not in meta:
                problems.append(f"{rel}: missing '{key}' in front matter")
        if meta.get("status") not in STATUSES:
            problems.append(f"{rel}: status must be one of {STATUSES}")
        spans = []
        for sp in meta.get("ce", []) if isinstance(meta.get("ce"), list) else [meta.get("ce", "")]:
            try:
                spans += parse_span(sp, struct)
            except ValueError as e:
                problems.append(f"{rel}: {e}")
        chapters.append({"file": f, "rel": rel, "meta": meta, "spans": spans,
                         "words": word_count(text), "text": story_text(text)})
    chapters.sort(key=lambda c: (c["meta"].get("book", 0), c["meta"].get("chapter", 0)))
    return chapters, problems


# ---------------------------------------------------------------- outputs

def fmt_span_list(spans) -> str:
    return ", ".join(spans) if isinstance(spans, list) else str(spans)


def build_contents(chapters) -> str:
    total = sum(c["words"] for c in chapters)
    by_status = defaultdict(int)
    for c in chapters:
        by_status[c["meta"].get("status")] += 1
    out = [GENERATED, "# Contents\n",
           f"**{len(chapters)} chapters, {total:,} words.** "
           + ", ".join(f"{by_status[s]} {s}" for s in STATUSES if by_status[s]) + "\n"]
    for b in range(1, 19):
        cs = [c for c in chapters if c["meta"].get("book") == b]
        if not cs:
            continue
        parva, title = BOOKS[b]
        out.append(f"\n## Book {b}: {parva} Parva, *{title}*\n")
        out.append("| # | Chapter | CE | Status | Words |\n|---|---------|----|--------|-------|")
        for c in cs:
            m = c["meta"]
            link = "../" + str(c["rel"]).replace("\\", "/")
            out.append(f"| {m.get('chapter')} | [{m.get('title')}]({link}) | {fmt_span_list(m.get('ce'))} "
                       f"| {m.get('status')} | {c['words']:,} |")
        out.append(f"\n*Book {b} so far: {sum(c['words'] for c in cs):,} words.*")
    return "\n".join(out) + "\n"


def ranges(nums):
    nums = sorted(nums)
    out, start, prev = [], None, None
    for n in nums:
        if start is None:
            start = prev = n
        elif n == prev + 1:
            prev = n
        else:
            out.append((start, prev))
            start = prev = n
    if start is not None:
        out.append((start, prev))
    return out


def build_coverage(chapters, struct) -> tuple[str, list[str]]:
    covered = defaultdict(set)
    owner = defaultdict(list)
    problems = []
    for c in chapters:
        for b, a, v1, v2 in c["spans"]:
            for v in range(v1, v2 + 1):
                if v in covered[(b, a)]:
                    owner[(b, a, v)].append(str(c["rel"]))
                covered[(b, a)].add(v)
    for (b, a, v), files in owner.items():
        problems.append(f"CE {b}.{a}.{v} is claimed by more than one chapter ({', '.join(files)})")
    all_v = sum(struct.values())
    done_v = sum(len(v) for v in covered.values())
    out = [GENERATED, "# Coverage of the Critical Edition\n",
           f"**{done_v:,} of {all_v:,} verses covered ({100 * done_v / all_v:.2f}%).** "
           "A verse is covered when a chapter's `ce` spans include it.\n",
           "| Book | Adhyāyas complete | Verses covered | Progress | Next uncovered |",
           "|------|-------------------|----------------|----------|----------------|"]
    details = []
    for b in range(1, 19):
        adhs = sorted(a for (bb, a) in struct if bb == b)
        tot = sum(struct[(b, a)] for a in adhs)
        cov = sum(len(covered[(b, a)]) for a in adhs)
        complete = sum(1 for a in adhs if len(covered[(b, a)]) == struct[(b, a)])
        pct = 100 * cov / tot
        bar = "█" * int(pct // 10) + "░" * (10 - int(pct // 10))
        nxt = next((f"{b}.{a}" + (f".{min(set(range(1, struct[(b, a)] + 1)) - covered[(b, a)])}" if covered[(b, a)] else "")
                    for a in adhs if len(covered[(b, a)]) < struct[(b, a)]), "none")
        out.append(f"| {b}. {BOOKS[b][0]} | {complete}/{len(adhs)} | {cov:,}/{tot:,} | `{bar}` {pct:.1f}% | {nxt} |")
        if cov:
            partial = [f"{b}.{a} (verses {', '.join(f'{x}-{y}' if x != y else str(x) for x, y in ranges(covered[(b, a)]))} of {struct[(b, a)]})"
                       for a in adhs if 0 < len(covered[(b, a)]) < struct[(b, a)]]
            done = [a for a in adhs if len(covered[(b, a)]) == struct[(b, a)]]
            details.append(f"\n### Book {b}\n")
            details.append("* Complete adhyāyas: " + (", ".join(f"{b}.{x}" + (f"–{b}.{y}" if y != x else "") for x, y in ranges(done)) or "none"))
            if partial:
                details.append("* Partly covered: " + "; ".join(partial))
    out.append("\n## Detail\n" + ("\n".join(details) if details else "\nNothing covered yet."))
    return "\n".join(out) + "\n", problems


def build_characters(chapters) -> str:
    data = json.loads(NAMES.read_text(encoding="utf-8"))
    out = [GENERATED, "# Character Index\n",
           "Where each person in `workbook/names.json` appears (name or dialogue name). "
           "Counts are mentions in the story text.\n",
           "| Person | Chapters (mentions) | First appears |", "|--------|---------------------|---------------|"]
    for p in sorted(data["people"], key=lambda p: p["name"]):
        forms = [p["name"]] + p.get("dialogue", [])
        rx = re.compile(r"\b(" + "|".join(map(re.escape, forms)) + r")\b")
        hits = []
        for c in chapters:
            n = len(rx.findall(c["text"]))
            if n:
                hits.append((c, n))
        where = ", ".join(f"{c['meta']['book']}.{c['meta']['chapter']} ({n})" for c, n in hits) or "not yet"
        first = f"{hits[0][0]['meta']['book']}.{hits[0][0]['meta']['chapter']}" if hits else "—"
        out.append(f"| {p['name']} | {where} | {first} |")
    return "\n".join(out) + "\n"


def build_names() -> str:
    data = json.loads(NAMES.read_text(encoding="utf-8"))
    out = [GENERATED.replace("tools/build_index.py", "tools/build_index.py from workbook/names.json"),
           "# Names and Spellings\n",
           "Edit [`names.json`](names.json), then run `python3 tools/build_index.py`. "
           "The narrator always uses the **Name** column. Characters may also use the "
           "**Dialogue** names when they speak. `tools/style_check.py` rejects the "
           "**Never write** spellings.\n",
           "| Name | IAST | Who | Also called (in the text) | Dialogue | Never write |",
           "|------|------|-----|---------------------------|----------|-------------|"]
    for p in sorted(data["people"], key=lambda p: (p["group"], p["name"])):
        out.append(f"| **{p['name']}** | {p['iast']} | {p['who']} | {', '.join(p.get('aka', []))} "
                   f"| {', '.join(p.get('dialogue', []))} | {', '.join(p.get('flag', []))} |")
    out.append("\n## Not in Vyasa's text\n")
    out.append("These names come from later works. `style_check.py` warns if they appear.\n")
    out.append("| Name | Ledger | Note |\n|------|--------|------|")
    for w in data.get("not_vyasa", []):
        out.append(f"| {w['name']} | [{w['ledger']}](../reference/AUTHENTICITY_LEDGER.md) | {w['note']} |")
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify outputs are current; do not write")
    args = ap.parse_args(argv)

    struct = load_structure()
    chapters, problems = load_chapters(struct)
    coverage, cov_problems = build_coverage(chapters, struct)
    problems += cov_problems
    outputs = {
        INDEX / "CONTENTS.md": build_contents(chapters),
        INDEX / "COVERAGE.md": coverage,
        INDEX / "CHARACTER_INDEX.md": build_characters(chapters),
        ROOT / "workbook" / "NAMES.md": build_names(),
    }
    stale = []
    for path, content in outputs.items():
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != content:
            stale.append(str(path.relative_to(ROOT)))
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    for p in problems:
        print("PROBLEM  " + p, file=sys.stderr)
    if args.check:
        for s in stale:
            print(f"out of date: {s}", file=sys.stderr)
        sys.exit(1 if (stale or problems) else 0)
    words = sum(c["words"] for c in chapters)
    print(f"{len(chapters)} chapters, {words:,} words; wrote {len(stale)} changed file(s)"
          + (f"; {len(problems)} problem(s)" if problems else ""))


if __name__ == "__main__":
    main()
